### ISSUE TITLE
Dev: 웹페이지 만들기

### ISSUE THREAD

**Issue by lwef** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#10]
## 작업 설명
> 웹페이지 마저 만들기

## TODO
- [x] 모아보기 페이지
- [x] 독후감 조회 페이지
- [x] 내가 쓴 독후감 목록 페이지
- [x] 헤더 수정

## 참고사항
http://localhost:3000/GatherReportPage >같은 책 독후감 모아보기 페이지
http://localhost:3000/ViewReportPage >독후감 상세정보 확인 페이지
http://localhost:3000/MyBookPage >내가 쓴 독후감 목록 페이지

**Comment by homubee** [comment]
ViewReportPage는 독후감 등록 페이지가 아니라 독후감 조회 페이지 맞나요?
작성 완료 버튼 같은 것도 있고, 각 컴포넌트들이 input 과 form으로 구성되어 있네요.
관련해서 확인 부탁드리고, 작업 사항에 대한 설명이 있으면 조금 더 좋을 것 같습니다.
