### ISSUE TITLE
Dev: 서버 함수 추가 작업 

### ISSUE THREAD

**Issue by ranief87** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#53]
## 작업 설명
> 서버에 필요한 함수 추가 구현

## TODO
- [x] get bookreport1
- [x] get bookreport2
- [x] get bookreport3
- [x] get bookreport4

**Comment by homubee** [comment]
민정님 get bookreport5와 get session은 모두 작업 완료된 부분입니다.
get bookreport1~4까지 작업 진행해주세요.
