### ISSUE TITLE
Dev: 프론트 추가 작업 사항

### ISSUE THREAD

**Issue by wonjinzz** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#59]
## 작업 설명
> 프론트 추가 작업 사항

## TODO
- [x] 독후감 박스 안에서 공백 여러 개 적용 안됨
- [x] 회원가입 페이지에 선호 장르 추가
- [x] ㄴ> 체크박스로 수정할것

## 참고사항
❌

**Comment by wonjinzz** [comment]
for문으로 하려다가 머리 아파서 하드코딩 했습니다

**Comment by wonjinzz** [comment]
그리고 봤을 때 가지런하지 않아서 div 사용해서 줄맞춤 했어요

**Comment by wonjinzz** [comment]
예외처리만

**Comment by wonjinzz** [comment]
보내는 쪽 text랑 DB 저장할 때 DB 쪽 text도 확인해봐야 하고 서버에서 줄 때도 확인해봐야 하고 클라이언트 쪽도 제대로 받았다고 가정했을 때 또 다시 잘 들어가는지 확인해야 되는데 보통 DB 쪽에서 저장될 때 예를 들어 4개를 1개로 저장하는 경우가 있거나 아니면 프론트에서 표시될 때 1개로 표시되는 경우가 있는 것 같습니다. 사실 공백 이슈는 크게 중요한 건 아닌 거 같은데 패스하면 어떨까요? 🤕

**Comment by homubee** [comment]
DB에 저장할 때는 문제가 없고요(개별 독후감 페이지는 정상적으로 공백이 표시되므로), html 구조 상 공백 문자가 여러 개 나올 시 한 개만 출력하도록 되어 있습니다. 즉, 프론트에서 표시될 때 1개로 표시되는 것입니다.

이 때문에, 실제 공백이 포함된 문장을 출력할 때는 `<p>`태그로 감사거나, 각 공백을 `<br>`이나 `&nbsp` 등을 통해 표현하게 됩니다. 아마 네이버 블로그, 티스토리 같은 글작성 플랫폼의 html 코드를 살펴보면 알 수 있을겁니다.

중요한 이슈이고 어렵다고 생각하지는 않지만, 시간 관계 상 여기에 신경 쓸 여력이 없으니 코사인 유사도 추천 시스템을 먼저 진행해주세요.

**Comment by homubee** [comment]
추가로, 현재 도서 분류별 관심도 정보를 내부적으로 checkA~checkJ로 지정된 객체를 전달하는 것으로 보입니다.

저희 api 문서 확인해보시면 아시겠지만, DB에 이러한 형태로 저장이 불가능하고, 단순히 문자열을 저장하도록 되어 있습니다.

예를 들어 각 분류에 대한 체크박스가
true, false, false, true, false, true, true, true, false, false
인 결과를 넘겨주었다면, 이를 변환하여
"1,0,0,1,0,1,1,1,0,0"
이라는 문자열로 만들어서, 이 문자열을 DB에 넘겨주셔야 합니다.

빠르게 반영하여 수정 부탁드립니다.
