### ISSUE TITLE
Dev: 서버 쪽 함수 추가하기

### ISSUE THREAD

**Issue by ranief87** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#6]
## 작업 설명
> 웹페이지 프론트에서 필요한 서버 함수 구현

## TODO
- [x] authentication, registration, get user 구현

**Comment by homubee** [comment]
TODO 내용을 좀 채워주세요~

**Comment by homubee** [comment]
커밋에 코멘트 자세히 달아두었으니 확인해주세요.

**Comment by homubee** [comment]
커밋에 코멘트로 피드백 달아두었으니 확인해주세요.
