### ISSUE TITLE
Dev: 백엔드 router 추천 구현

### ISSUE THREAD

**Issue by ranief87** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#62]
## 작업 설명
> get recommend 구현

## TODO
- [x] recommend

## 참고사항

**Comment by ranief87** [comment]
<img width="374" alt="화면 캡처 2022-06-07 024807" src="https://user-images.githubusercontent.com/62322084/172216664-e261510e-189a-4078-a348-53d30489475b.png">

이건 react 앱에서 뜨고 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/62322084/172216985-b83ada76-cf63-4697-844d-510287bc9fdb.png">

이건 vs에서 뜨는데 해결이 잘 안됩니다. 어디가 문제인지 잘 모르겠어서;;

**Comment by homubee** [comment]
일단 async await 안써서 문제 발생하는 것 같습니다.
![오류 이미지](https://user-images.githubusercontent.com/83688807/172283825-9fd16f90-00bc-48a3-b698-da3a4f298eb2.png)
보면 프로미스 객체만 리턴하고 제대로 된 정보를 출력하지 못하고 있습니다.

또한, 다른 곳에서 작업하신 것 확인해보시면 아시겠지만 pool.query해서 받아온 데이터는 테이블 정보가 아니라 db의 각종 부가 정보까지 포함하는 정보입니다. 해당 내용을 빼고 나머지만 가져와야 합니다.

![userid 부가정보](https://user-images.githubusercontent.com/83688807/172283885-302bfe2f-edf1-4209-b0f4-76eee120659a.png)

예를 들어 유저 정보를 pool.query해서 가져오고 그대로 console.log로 출력한 것입니다. 아래에 보면 줄줄이 부가 정보가 따라오고 있습니다. 지금 민정님 코드로는 이 부가정보까지 전부 합쳐서 배열을 만들었으니 내용이 전혀 동작하질 않습니다.

위에서 볼 수 있듯 일반적으로 테이블 정보는 [0]에 담겨 있습니다. 그러나 그 내부 형태가 json으로 되어 있기 때문에, 원하는 대로 사용하려면 개별 요소를 추출하여 새로운 배열을 만드셔야 합니다.

**Comment by ranief87** [comment]
혹시 개별 요소 어떻게 나눠서 가져오는지 아시나요? 찾아도 잘 모르겠어서
<img width="479" alt="image" src="https://user-images.githubusercontent.com/62322084/172354617-e920b688-b9fc-404d-82af-5ba12666885b.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/62322084/172354752-69125275-c730-4d84-a233-690c28227456.png">

여기서 'userid:' 이쪽이 없이 순수하게 아이디만 가져오는 방법이 있나요? column 값만

**Comment by ranief87** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/62322084/172461904-05b217c3-64f1-4821-b8df-84543fe1efa7.png">
끝! 도서 정보 가져옵니다.

**Comment by homubee** [comment]
몇가지 전달사항 있어 알려드립니다.

1. 리턴되는 데이터 형식
![배열에 배열](https://user-images.githubusercontent.com/83688807/172523014-3bcd4374-6266-409e-b4a7-4f87f02d965c.png)
지금 출력해보면
[[{도서 정보1}], [{도서 정보2}], [{도서 정보3}], [{도서 정보4}]] 구조로 되어 있습니다.
배열에 배열이 들어가 있는 상태입니다. 저희 다른 백 부분 구현한 내용 보면 다음과 같이 되어 있습니다.
[{도서 정보1}, {도서 정보2}, {도서 정보3}, {도서 정보4}]
각 요소를 추출해서 배열 안에 json 객체가 있는 형태로 구성해주세요.

2. 동작 테스트
제가 이전에 제공해드렸던 테스트 데이터, 혹은 그에 준하는 규모의 데이터로 테스트 부탁드립니다. 현재에는 행렬의 크기가 워낙 작다보니 원하는 기능대로 모두 동작하는지 확인이 어렵습니다.

3. 변수명 수정
변수명이 예를 들어 ilen 이런 식으로 축약형으로 되어 있는 부분이 많은데, 알아보기 어렵습니다. 변수명이 길어지더라도 풀네임을 적어주세요. isbnLength 이런식으로 CamelCase로 작성해주시면 감사하겠습니다. 다른 프론트분들이 코사인 유사도 작업하는데 참고하시기 어려울 것 같아서 부탁드립니다.

1, 2번 작업 부탁드리고, 3번은 시간 나면 진행 부탁드립니다.
일단 기본적인 동작에는 문제가 없으니 병합부터 진행하려고 합니다. 풀리퀘 넣어주세면 병합하고, 민정님 추가 수정사항은 그 이후에 새로 브랜치 파서 진행하시면 될 것 같습니다.

혹시 일정 상 진행이 어려우시면 꼭 말씀해주세요. 작업을 좀 재조정해보도록 노력하겠습니다.
