### ISSUE TITLE
Dev: 오타 수정

### ISSUE THREAD

**Issue by wonjinzz** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#72]
## 작업 설명
> 오타 수정 (시각적인 부분)

## TODO
- [x] 사회학 -> 사회과학
- [x] 가지런하게
- [x] 추천 도서 불러오기

## 참고사항
❌

**Comment by homubee** [comment]
이거 동작 테스트 하신건가요? 추천 기능이 전혀 동작하질 않아서 여쭤봅니다.
